"""init

Revision ID: c98ca07965d2
Revises: 
Create Date: 2024-08-02 13:25:13.615948

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c98ca07965d2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("feed_url", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("link", sa.String(), nullable=False),
        sa.Column(
            "predicted_label",
            sa.Enum("POOR", "AVERAGE", "GOOD", name="label"),
            nullable=True,
        ),
        sa.Column(
            "label", sa.Enum("POOR", "AVERAGE", "GOOD", name="label"), nullable=True
        ),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("author", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("comments", sa.String(), nullable=True),
        sa.Column("enclosure", sa.String(), nullable=True),
        sa.Column("guid", sa.String(), nullable=True),
        sa.Column("pubDate", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_item")),
        sa.UniqueConstraint("title", "feed_url", name=op.f("uq_item_title_feed_url")),
    )
    op.create_index(
        op.f("ix_item_feed_url_created_at_predicted_label"),
        "item",
        ["feed_url", "created_at", "predicted_label"],
        unique=False,
    )
    op.create_index(
        op.f("ix_item_feed_url_title"), "item", ["feed_url", "title"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_item_feed_url_title"), table_name="item")
    op.drop_index(
        op.f("ix_item_feed_url_created_at_predicted_label"), table_name="item"
    )
    op.drop_table("item")
    # ### end Alembic commands ###
